x1 = int(input('Qual o primeiro ponto x? '))
y1 = int(input('Qual o primeiro ponto y? '))
x2 = int(input('Qual o segundo ponto x? '))
y2 = int(input('Qual o segundo ponto y? '))
d = ((x2 - x1)**2 + (y2 - y1)**2)**(1/2)
print('A distância dos pontos P({}, {}) e Q({}, {}) é {}.'.format(x1, y1, x2, y2, d))
